using Dapper;
using LirsPortal.Api.Data;
using LirsPortal.Api.Models;

namespace LirsPortal.Api.Repositories;

/// <summary>
/// Handles SQL database transactions and queries specifically for tax payments and return validations.
/// Implements IPaymentRepository to allow seamless mocking in automated unit tests.
/// </summary>
public class PaymentRepository(DbConnectionFactory factory) : IPaymentRepository
{
    /// <summary>
    /// Fetches a specific tax return to verify its status and statutory due amount
    /// before permitting any payment to be recorded against it.
    /// </summary>
    public async Task<TaxReturn?> GetReturnAsync(int returnId)
    {
        const string sql = @"
            SELECT ReturnId, TaxpayerId, TaxYear, DeclaredIncome, TaxDue, Status
            FROM TaxReturns 
            WHERE ReturnId = @ReturnId";

        using var db = factory.Create();
        return await db.QuerySingleOrDefaultAsync<TaxReturn>(sql, new { ReturnId = returnId });
    }

    /// <summary>
    /// Sums up all payments already completed against this tax return.
    /// If no payments have been made yet, COALESCE ensures it safely returns 0.00.
    /// </summary>
    public async Task<decimal> GetTotalPaidAsync(int returnId)
    {
        const string sql = "SELECT COALESCE(SUM(Amount), 0) FROM Payments WHERE ReturnId = @ReturnId";
        
        using var db = factory.Create();
        return await db.QuerySingleAsync<decimal>(sql, new { ReturnId = returnId });
    }

    /// <summary>
    /// Saves a newly validated payment record to the Payments table.
    /// 
    /// Senior Engineer Note on 'OUTPUT INSERTED.PaymentId':
    /// In SQL Server, the PaymentId is an auto-incrementing IDENTITY column generated by the database.
    /// Rather than executing an INSERT and then running a second query (like SELECT @@IDENTITY)
    /// which can cause race conditions in high-concurrency systems, the 'OUTPUT INSERTED' clause
    /// atomically returns the brand new identity ID in the exact same database trip!
    /// </summary>
    public async Task<int> SaveAsync(PaymentRequest request)
    {
        const string sql = @"
            INSERT INTO Payments (ReturnId, Amount, PaidOn, Channel)
            OUTPUT INSERTED.PaymentId
            VALUES (@ReturnId, @Amount, SYSDATETIME(), @Channel);";

        using var db = factory.Create();

        // ExecuteScalarAsync executes the query and returns the first column of the first row (the PaymentId integer).
        return await db.ExecuteScalarAsync<int>(sql, request);
    }

    /// <summary>
    /// Checks whether an external bank or gateway transaction reference has already been logged.
    /// Senior Engineer Note on Idempotency:
    /// In financial processing, network timeouts can cause a bank or client to retry a payment.
    /// Checking this reference prevents double-crediting or duplicate deductions.
    /// </summary>
    public async Task<bool> ExistsByReferenceAsync(string reference)
    {
        const string sql = "SELECT COUNT(1) FROM ComplianceLogs WHERE Event LIKE '%' + @Ref + '%'";
        using var db = factory.Create();
        var count = await db.ExecuteScalarAsync<int>(sql, new { Ref = reference });
        return count > 0;
    }
}
